# define third-party library paths
# CHANGE YOUR CUDA PATH IF IT IS NOT THIS
CVL_HOME=/idiap/group/cvl

CUDA_DIR := ${CVL_HOME}/local/usr/local/cuda-7.5
#CUDA_DIR := /usr/local/cuda

# CHANGE YOUR CUDA ARCH IF IT IS NOT THIS
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
    -gencode arch=compute_20,code=sm_21 \
    -gencode arch=compute_30,code=sm_30 \
    -gencode arch=compute_35,code=sm_35
# CHANGE YOUR MKL PATH IF IT IS NOT THIS
BLAS_DIR := /Opt/OpenBlas
# CHANGE YOUR MATLAB PATH IF IT IS NOT THIS
# PUT ALL OTHER INCLUDE AND LIB DIRECTORIES HERE
# Whatever else you find you need goes here.
INCLUDE_DIRS :=   /usr/local/include
LIBRARY_DIRS :=  /usr/lib /usr/local/lib
# DEFINE THE CXX PATH
CXX=g++
BUILD_DIR=build
DISTRIBUTE_DIR=distribute
